### ISSUE TITLE
Uncaught TypeError: Cannot read property 'presenter' of null

### ISSUE THREAD

**Issue by v3ss0n** [olmokramer/atom-cursor-blink-interval#1]
[Enter steps to reproduce below:]
1. Click dragging to move a tab from one pane to another
2. Causes error and do not move tab.

**Atom Version**: 0.211.0-852456f
**System**: "Sabayon Linux
**Thrown From**: [cursor-blink-interval](https://github.com/olmokramer/atom-cursor-blink-interval) package, v0.3.0
### Stack Trace

Uncaught TypeError: Cannot read property 'presenter' of null

```
At /home/v3ss/.atom/packages/cursor-blink-interval/lib/cursor-blink-interval.coffee:31

TypeError: Cannot read property 'presenter' of null
  at CursorBlinkInterval.updateEditors (/home/v3ss/.atom/packages/cursor-blink-interval/lib/cursor-blink-interval.coffee:31:61)
  at /home/v3ss/.atom/packages/cursor-blink-interval/lib/cursor-blink-interval.coffee:1:2
  at /home/v3ss/.atom/packages/cursor-blink-interval/node_modules/atom-package-config-observer/atom-package-config-observer.js:53:16
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /home/v3ss/.atom/packages/cursor-blink-interval/node_modules/atom-package-config-observer/atom-package-config-observer.js:79:32
  at /opt/atom/resources/app.asar/src/workspace.js:281:16
  at /opt/atom/resources/app.asar/src/workspace.js:338:18
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/opt/atom/resources/app.asar/src/pane-container.js:375:27)
  at /opt/atom/resources/app.asar/src/pane-container.js:362:26
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/opt/atom/resources/app.asar/src/pane.js:326:20)
  at Pane.module.exports.Pane.moveItemToPane (/opt/atom/resources/app.asar/src/pane.js:415:19)
  at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/opt/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:720:20)
  at TabBarView.module.exports.TabBarView.onDrop (/opt/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:638:23)
  at space-pen-ul.<anonymous> (/opt/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -7:05.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -7:04.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -6:58.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:58.2.0 core:save (atom-text-editor.editor.is-focused)
     -6:57.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -6:56.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -6:56.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:56.4.0 build:trigger (atom-text-editor.editor)
     -4:12.5.0 core:select-all (atom-text-editor.editor.is-focused)
     -4:11.5.0 core:copy (atom-text-editor.editor.is-focused)
     -4:09.8.0 core:select-all (atom-text-editor.editor.is-focused)
     -4:09.4.0 core:paste (atom-text-editor.editor.is-focused)
     -4:08.7.0 core:save (atom-text-editor.editor.is-focused)
  4x -3:46.3.0 core:copy (atom-text-editor.editor.is-focused)
     -3:23.7.0 core:paste (atom-text-editor.editor.is-focused)
  2x -3:10 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-ruby-on-rails",
      "mobile-preview",
      "atom-html-preview",
      "color-picker",
      "run-command",
      "runcoderun",
      "whitespace",
      "svg-preview",
      "autosave",
      "autocomplete-jedi",
      "autocomplete-plus-async",
      "cute-cursor",
      "pulsing-cursor",
      "neon-selection",
      "atom-lint",
      "animation-showcase",
      "tree-view-open-files",
      "autocomplete",
      "ease-blink",
      "highlight-line",
      "minimap-highlight-selected",
      "minimap",
      "markdown-writer",
      "atom-alignment",
      "autocomplete-atom-api",
      "fancy-input",
      "sublime-tabs",
      "spell-check",
      "tool-bar-main",
      "tool-bar",
      "flex-tool-bar",
      "atom-ternjs",
      "gutter-shadow",
      "local-history",
      "tab-rename",
      "open-in",
      "pigments",
      "linter",
      "goto"
    ],
    "ignoredNames": [
      "*.pyc",
      "/home/v3ss/workspace/phwa.be/condaenv",
      "/home/v3ss/workspace/phwa.be/pypyenv",
      "*.zip",
      "*.tar",
      ".hg"
    ],
    "autoHideMenuBar": true,
    "themes": [
      "steam-pirate-ui",
      "steam-pirate-syntax"
    ]
  },
  "cursor-blink-interval": {
    "cursorBlinkInterval": 1500
  }
}
```
### Installed Packages

``` coffee
# User
Termrk, v0.1.17
atom-beautify, v0.28.5
auto-reveal-in-sidebar, v0.5.0
autocomplete-plus-python-jedi, v0.3.6
autohide-tree-view, v0.20.2
block-cursor, v0.13.1
block-travel, v1.0.2
build, v0.38.0
cursor-blink-interval, v0.3.0
editorconfig, v1.0.0
file-icons, v1.5.7
file-type-icons, v0.7.0
hashrocket, v0.4.8
highlight-column, v0.4.3
highlight-selected, v0.10.1
language-javascript-better, v1.5.0
language-nim, v0.2.2
linter-coffeelint, v0.3.2
linter-csslint, v0.0.13
linter-flake8, v1.4.2
linter-jshint, v0.1.6
linter-tidy, v1.0.1
linter-xmllint, v0.0.6
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-selection, v4.2.0
pdf-view, v0.22.0
script-runner, v1.8.3
steam-pirate-syntax, v0.3.0
steam-pirate-ui, v0.5.1
symbols-tree-view, v0.9.3
tabs-to-spaces, v0.11.0
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
Hey, thanks for the report. Sadly, I don't know when I'll have time to look at this, but I'll try to make some time this weekend.

**Comment by olmokramer** [comment]
I can't reproduce this. Does this still happen? Do any of the packages you use have a panel of sorts that has an `atom-text-editor` component in them?

**Comment by justo** [comment]
It only happens when you drag a tab into an empty pane. So if you turn off "destroy empty panes" in settings and then try to move a tab into it it will crash. Looks like `atom.views.getView(editor).component` doesn't exist yet maybe?

**Comment by olmokramer** [comment]
Hey, it does happen now. Yay, i guess... Thanks for the report :)

**Comment by olmokramer** [comment]
I found the issue. v0.3.1 should fix it. Please let me know if it's working for you

**Comment by v3ss0n** [comment]
thanks i will try soon!

**Comment by justo** [comment]
Fast fix! Works well for me now, thanks.
